# Can mix and match application.properties and application.yml
pv:
  jms:
    username: JMS Username
    password: somePASS
    dburl: SomeURL

# New file
---
spring:
  profiles: german
# Spring profile overwrites the above config info
pv:
  jms:
    username: JMS Username IN GEEERRRRRMAN!!!
